In [1]:
import torch

In [6]:
rand = torch.randint(-100, 100, (6,))
print(rand)

tensor([ 45,  64, -21,  54,  -8, -61])


In [7]:
zeros = torch.zeros(6,2,3)
print(zeros)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [8]:
ones = torch.ones(1,2)
print(ones)

tensor([[1., 1.]])


In [10]:
arange = torch.arange(0, 10, 1)
print(arange)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
linspace = torch.linspace(1, 5, steps=7)
print(linspace)

tensor([1.0000, 1.6667, 2.3333, 3.0000, 3.6667, 4.3333, 5.0000])


In [17]:
logspace = torch.logspace(0, 2, steps=5)
print(logspace)

tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])


In [21]:
eye = torch.eye(5)
print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [66]:
triangle_lower = torch.tril(torch.ones(5,5))
print(triangle_lower)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [67]:
triangle_upper = torch.triu(torch.ones(5,5))
print(triangle_upper)

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])


In [ ]:
a = torch.empty(2,3)
b = torch.ones_like(a)
c = torch.zeros_like(a)
d = torch.empty_like(a)

print(a)
print(b)
print(c)
print(d)

tensor([[1.7046e+22, 3.6061e-41, 0.0000e+00],
        [1.4013e-45, 8.9683e-44, 0.0000e+00]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[2.1707e-18, 7.0952e+22, 1.7748e+28],
        [1.8176e+31, 7.2708e+31, 5.0778e+31]])


In [59]:
t1 = torch.tensor([1,2,3,4,5])
t2 = torch.tensor([1,2,3,4,5])
print(torch.cat((t1, t2), dim=0))

tensor([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])


In [ ]:
probabilities = torch.tensor([0.2, 0.8])
print(torch.multinomial(probabilities, 10, replacement=True)) # how many successes, if 80% chance of success, in 10 trials  

tensor([1, 1, 1, 0, 1, 1, 0, 1, 1, 1])
