In [1]:
import torch

In [6]:
rand = torch.randint(-100, 100, (6,))
print(rand)

tensor([ 45,  64, -21,  54,  -8, -61])


In [7]:
zeros = torch.zeros(6,2,3)
print(zeros)

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [8]:
ones = torch.ones(1,2)
print(ones)

tensor([[1., 1.]])


In [10]:
arange = torch.arange(0, 10, 1)
print(arange)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [15]:
linspace = torch.linspace(1, 5, steps=7)
print(linspace)

tensor([1.0000, 1.6667, 2.3333, 3.0000, 3.6667, 4.3333, 5.0000])


In [17]:
logspace = torch.logspace(0, 2, steps=5)
print(logspace)

tensor([  1.0000,   3.1623,  10.0000,  31.6228, 100.0000])


In [21]:
eye = torch.eye(5)
print(eye)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
